import { collection, collectionGroup, defineModule, field } from '@deeptimes/directus-schema-kit'

const group = 'course_catalog'

export default defineModule({
  id: 'catalog',
  version: '1.0.0',
  groups: [
    collectionGroup({ name: group, label: '课程内容', icon: 'school', order: 10 }),
  ],
  collections: [
    collection({
      name: 'course_categories',
      label: '课程分类',
      icon: 'category',
      group,
      order: 10,
      displayTemplate: '{{name}}',
      fields: [
        field.sort(),
        ...field.audit(),
        field.status(),
        field.string('slug', { label: '分类标识', required: true, unique: true, width: 'half' }),
        field.string('name', { label: '分类名称', required: true, width: 'half' }),
        field.string('icon', { label: '图标', width: 'half' }),
        field.text('description', { label: '分类说明' }),
      ],
    }),
    collection({
      name: 'courses',
      label: '课程',
      icon: 'menu_book',
      group,
      order: 20,
      displayTemplate: '{{title}}',
      fields: [
        field.sort(),
        ...field.audit(),
        field.status(),
        field.string('slug', { label: '课程标识', required: true, unique: true, width: 'half' }),
        field.string('title', { label: '课程名称', required: true, width: 'half' }),
        field.string('subtitle', { label: '副标题' }),
        field.text('description', { label: '课程介绍', required: true, interface: 'input-rich-text-html' }),
        field.string('cover_url', { label: '封面地址', interface: 'input-code' }),
        field.m2o('category', {
          label: '课程分类', collection: 'course_categories', required: true,
          onDelete: 'RESTRICT', displayTemplate: '{{name}}', width: 'half',
        }),
        field.m2o('instructor', {
          label: '讲师', collection: 'directus_users', onDelete: 'SET NULL',
          displayTemplate: '{{first_name}} {{last_name}}', width: 'half',
        }),
        field.string('level', {
          label: '难度', required: true, defaultValue: 'beginner', width: 'half',
          interface: 'select-dropdown', display: 'labels',
          options: { choices: [
            { text: '入门', value: 'beginner' },
            { text: '进阶', value: 'intermediate' },
            { text: '高级', value: 'advanced' },
          ] },
        }),
        field.integer('duration_minutes', { label: '总时长（分钟）', required: true, defaultValue: 0, width: 'half' }),
        field.decimal('price', { label: '售价', required: true, precision: 10, scale: 2, width: 'half' }),
        field.decimal('original_price', { label: '原价', precision: 10, scale: 2, width: 'half' }),
        field.boolean('is_featured', { label: '推荐课程', defaultValue: false, width: 'half' }),
        field.integer('sales_count', { label: '销量', defaultValue: 0, readonly: true, width: 'half' }),
        field.dateTime('published_at', { label: '发布时间', width: 'half' }),
        field.json('metadata', { label: '扩展信息', note: '用于测试 JSON 字段和可扩展课程属性。' }),
      ],
    }),
    collection({
      name: 'course_chapters',
      label: '课程章节',
      icon: 'segment',
      group,
      order: 30,
      displayTemplate: '{{title}}',
      fields: [
        field.sort(),
        ...field.audit(),
        field.status(),
        field.string('slug', { label: '章节标识', required: true, unique: true, width: 'half' }),
        field.string('title', { label: '章节名称', required: true, width: 'half' }),
        field.m2o('course', {
          label: '所属课程', collection: 'courses', required: true,
          onDelete: 'CASCADE', displayTemplate: '{{title}}',
        }),
        field.text('summary', { label: '章节简介' }),
      ],
    }),
    collection({
      name: 'course_lessons',
      label: '课时',
      icon: 'play_circle',
      group,
      order: 40,
      displayTemplate: '{{title}}',
      fields: [
        field.sort(),
        ...field.audit(),
        field.status(),
        field.string('slug', { label: '课时标识', required: true, unique: true, width: 'half' }),
        field.string('title', { label: '课时名称', required: true, width: 'half' }),
        field.m2o('chapter', {
          label: '所属章节', collection: 'course_chapters', required: true,
          onDelete: 'CASCADE', displayTemplate: '{{title}}',
        }),
        field.text('content', { label: '课时内容', interface: 'input-rich-text-html' }),
        field.string('video_url', { label: '视频地址' }),
        field.integer('duration_seconds', { label: '时长（秒）', required: true, defaultValue: 0, width: 'half' }),
        field.boolean('is_free', { label: '免费试看', defaultValue: false, width: 'half' }),
        field.json('attachments', { label: '课时附件' }),
      ],
    }),
  ],
  cleanupCollections: ['course_categories', 'courses', 'course_chapters', 'course_lessons'],
})
