import { collection, collectionGroup, defineSchema, field, relation } from '@deeptimes/directus-schema-kit'

const group = 'course_catalog_v2'

export default defineSchema({
  groups: [
    collectionGroup({ name: group, label: '课程内容 V2', icon: 'school', order: 20 }),
  ],
  collections: [
    collection({
      name: 'course_categories_v2',
      label: '课程分类 V2',
      icon: 'category',
      group,
      order: 10,
      displayTemplate: '{{name}}',
      fields: [
        field.sort(),
        ...field.audit(),
        field.status(),
        field.string('slug', { label: '分类标识', required: true, unique: true }),
        field.string('name', { label: '分类名称', required: true }),
        field.string('icon', { label: '图标' }),
        field.markdown('description', { label: '分类说明' }),
      ],
    }),
    collection({
      name: 'courses_v2',
      label: '课程 V2',
      icon: 'menu_book',
      group,
      order: 20,
      displayTemplate: '{{title}}',
      fields: [
        field.sort(),
        ...field.audit(),
        field.status(),
        field.string('slug', { label: '课程标识', required: true, unique: true}),
        field.string('title', { label: '课程名称', required: true}),
        field.string('subtitle', { label: '副标题' }),
        field.markdown('description', { label: '课程介绍', required: true }),
        field.tags('keywords', { label: '关键词', type: 'json' }),
        field.string('level', {
          label: '难度', required: true, defaultValue: 'beginner', width: 'half',
          interface: 'select-dropdown', display: 'labels',
          options: {
            choices: [
              { text: '入门', value: 'beginner' },
              { text: '进阶', value: 'intermediate' },
              { text: '高级', value: 'advanced' },
            ],
          },
        }),
        field.integer('duration_minutes', { label: '总时长（分钟）', required: true, defaultValue: 0}),
        field.decimal('price', { label: '售价', required: true, precision: 10, scale: 2}),
        field.decimal('original_price', { label: '原价', precision: 10, scale: 2}),
        field.toggle('is_featured', { label: '推荐课程', defaultValue: false, labelOn: '推荐', labelOff: '普通' }),
        field.integer('sales_count', { label: '销量', defaultValue: 0, readonly: true}),
        field.dateTime('published_at', { label: '发布时间'}),
        field.code('metadata', { label: '扩展信息', type: 'json', language: 'json' }),
      ],
    }),
    collection({
      name: 'course_chapters_v2',
      label: '课程章节 V2',
      icon: 'segment',
      group,
      order: 30,
      displayTemplate: '{{title}}',
      fields: [
        field.sort(),
        ...field.audit(),
        field.status(),
        field.string('slug', { label: '章节标识', required: true, unique: true, width: 'half' }),
        field.string('title', { label: '章节名称', required: true, width: 'half' }),
        field.markdown('summary', { label: '章节简介' }),
      ],
    }),
    collection({
      name: 'course_lessons_v2',
      label: '课时 V2',
      icon: 'play_circle',
      group,
      order: 40,
      displayTemplate: '{{title}}',
      fields: [
        field.sort(),
        ...field.audit(),
        field.status(),
        field.string('slug', { label: '课时标识', required: true, unique: true, width: 'half' }),
        field.string('title', { label: '课时名称', required: true, width: 'half' }),
        field.markdown('content', { label: '课时内容' }),
        field.string('video_url', { label: '视频地址' }),
        field.integer('duration_seconds', { label: '时长（秒）', required: true, defaultValue: 0, width: 'half' }),
        field.toggle('is_free', { label: '免费试看', defaultValue: false, labelOn: '免费', labelOff: '付费' }),
      ],
    }),
    collection({
      name: 'course_tags_v2',
      label: '课程标签 V2',
      icon: 'sell',
      group,
      order: 50,
      displayTemplate: '{{name}}',
      fields: [
        field.string('name', { label: '标签名称', required: true, unique: true }),
      ],
    }),
    collection({
      name: 'course_languages_v2',
      label: '课程语言 V2',
      icon: 'language',
      group,
      order: 60,
      displayTemplate: '{{name}}',
      fields: [
        field.string('code', { label: '语言代码', required: true, unique: true, width: 'half' }),
        field.string('name', { label: '语言名称', required: true, width: 'half' }),
      ],
    }),
    collection({
      name: 'lesson_text_blocks_v2',
      label: '文本内容块 V2',
      icon: 'notes',
      group,
      order: 70,
      fields: [field.markdown('content', { label: '文本内容', required: true })],
    }),
    collection({
      name: 'lesson_code_blocks_v2',
      label: '代码内容块 V2',
      icon: 'code',
      group,
      order: 80,
      fields: [field.code('content', { label: '代码内容', type: 'text', lineNumber: true })],
    }),
  ],
  relations: [
    relation.o2m({
      collection: 'course_categories_v2',
      field: 'courses',
      relatedCollection: 'courses_v2',
      relatedField: 'category',
      onDelete: 'RESTRICT',
      fieldOptions: { label: '课程' },
    }),
    relation.m2o({
      collection: 'courses_v2',
      field: 'instructor',
      relatedCollection: 'directus_users',
      onDelete: 'SET NULL',
      fieldOptions: { label: '讲师', width: 'half', displayTemplate: '{{first_name}} {{last_name}}' },
    }),
    relation.o2m({
      collection: 'courses_v2',
      field: 'chapters',
      relatedCollection: 'course_chapters_v2',
      relatedField: 'course',
      onDelete: 'CASCADE',
      fieldOptions: { label: '章节' },
    }),
    relation.o2m({
      collection: 'course_chapters_v2',
      field: 'lessons',
      relatedCollection: 'course_lessons_v2',
      relatedField: 'chapter',
      onDelete: 'CASCADE',
      fieldOptions: { label: '课时' },
    }),
    relation.image({
      collection: 'courses_v2',
      field: 'cover',
      onDelete: 'SET NULL',
      fieldOptions: { label: '课程封面' },
    }),
    relation.file({
      collection: 'courses_v2',
      field: 'syllabus',
      onDelete: 'SET NULL',
      fieldOptions: { label: '课程大纲' },
    }),
    relation.m2m({
      collection: 'courses_v2',
      field: 'tags',
      relatedCollection: 'course_tags_v2',
      fieldOptions: { label: '课程标签' },
    }),
    relation.files({
      collection: 'course_lessons_v2',
      field: 'attachments',
      fieldOptions: { label: '课时附件' },
    }),
    relation.translations({
      collection: 'courses_v2',
      field: 'translations',
      languagesCollection: 'course_languages_v2',
      fieldOptions: { label: '课程翻译' },
    }),
    relation.m2a({
      collection: 'course_lessons_v2',
      field: 'blocks',
      allowedCollections: ['lesson_text_blocks_v2', 'lesson_code_blocks_v2'],
      fieldOptions: { label: '课时内容块' },
    }),
  ],
})
