shellEmulator: true

trustPolicy: no-downgrade

trustPolicyExclude:
  - chokidar@4.0.3
  - jose@4.15.9

onlyBuiltDependencies:
  - argon2
  - esbuild
  - isolated-vm
  - oracledb
  - protobufjs
  - sharp
  - sqlite3
  - vue-demi
